apiVersion: v1
kind: Service
metadata:
  name: hokudai-webbleworld
  namespace: default
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hokudai-webbleworld
  sessionAffinity: None
  type: LoadBalancer
